name: TweetFlow

on:
  push:
    branches: [ main ]
    paths:
      - Tweet-Service/**
      - .github/workflows/tweet-service.yml
  pull_request:
    branches: [ master ]
    paths:
      - Tweet-Service/**
      - .github/workflows/tweet-service.yml

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Tweet-Service
    - name: Build
      run: dotnet build --no-restore 
      working-directory: Tweet-Service
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Tweet-Service
    - name: Build and Push Image
      uses: mr-smithers-excellent/docker-build-push@v5.5
      with:
        image: samirz5/tweet-service
        tags: latest
        registry: docker.io
        dockerfile: Tweet-Service/Dockerfile
        directory: .
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
